### ISSUE TITLE
1.19.3 Item Frame Control

### ISSUE THREAD

**Issue by briliston** [dragon3025/My-Datapacks#10]
Can't unfix an item frame even when filling its block with stone

**Screenshots**
![image](https://user-images.githubusercontent.com/51443999/215871562-726d8542-7123-4952-b6ce-e5dad108b395.png)
![image](https://user-images.githubusercontent.com/51443999/215871704-80d7e24a-5a00-4b48-b0d1-1beca2de5b6b.png)

**Comment by dragon3025** [comment]
Are you using the newest version (updated 2 weeks ago)? The newest version now uses the command `/trigger frame_adjust_lost` to fix all item frames that are covered or frames that are invisible without an item in it, are you using that command? I tested it and I'm not having this issue.
