### ISSUE TITLE
[1.18.2] [Bell Finds All Raiders]

### ISSUE THREAD

**Issue by iogeg** [dragon3025/My-Datapacks#11]
What feature would you like to be added?
Pls make 1.18 ver

**Comment by dragon3025** [comment]
Here's a link to an older version of my Datapacks, the Bell Finds All Raiders pack will work for 1.18.2: [link](https://github.com/dragon3025/My-Datapacks/archive/47e16016068315ca5d70e70bef3502085b002f94.zip)

 (you can edit the pack.mcmeta pack format to 9, to let the game know it's not out of date).
