### ISSUE TITLE
[1.20.4] [Bell Finds All Raiders]

### ISSUE THREAD

**Issue by AkaiNoval** [dragon3025/My-Datapacks#12]
**Describe the bug**
Nothing changes. Bell still has default behavior; it only give raiders in 32 radius the glowing effect.

**To Reproduce**
Using the bell when being raided, if the raiders are too far, over 32 blocks. Its just not working anymore. 

**Expected behavior**
All raiders should be highlighted when ringing the bell.

**Comment by dragon3025** [comment]
Where the mobs part of a raid. I tested just now by:
- Starting a raid.
- Capturing a Pillager in a Boat.
- Killed all, but the 1 Pillager in a Boat.
- Filled a row of blocks 96 blocks away from a Bell and TP'd the Pillager to the end of that block.
- Rang the Bell and the Pillager was given the Glowing effect.

**Comment by AkaiNoval** [comment]
I'll test in new server and let you know soon.

**Comment by AkaiNoval** [comment]
Just test on a new server and i figured it out. its not a bug from the
datapack, phew!. Its because the view distance from the server is only 10
and players view render distance is also low thats why far away mobs doesnt
show up.
