### ISSUE TITLE
No Surface Creeper Grief - Revived

### ISSUE THREAD

**Issue by mrburger** [dragon3025/My-Datapacks#13]
I noticed a while back you removed No Surface Creeper Grief from PMC and never reuploaded it.

I spent some time updating the pack to have depth-based creeper attributes, so a sort of riff on the concept.
Deepslate Creepers are now more dangerous as support mobs, and have mining fatigue applied as a lingering potion, as well as higher explosive power.

**Comment by dragon3025** [comment]
That's cool that you made another pack based off of it. Feel free to upload anywhere.

**Comment by alyx404** [comment]
@mrburger Finally sourced here as modrinth dont have issue link or so.
Would you mind update Depth Based Creeper Griefing to 1.20.5? much thanks.

**Comment by dragon3025** [comment]
Here's an updated version of the datapack, it works for 1.20.3 to 1.20.5:
[No Surface Creeper Grief.zip](https://github.com/dragon3025/My-Datapacks/files/15143855/No.Surface.Creeper.Grief.zip)
