### ISSUE TITLE
[1.20.1] [Bell Finds All Raiders]

### ISSUE THREAD

**Issue by andromeda926** [dragon3025/My-Datapacks#17]
What feature would you like to be added?
1.20.1 version please? Thank you!

**Comment by dragon3025** [comment]
I compared the pack formats of 1.20.1 and 1.20.2. My 1.20.2 Data Pack would work in 1.20.1, so here's a copy of that pack with the pack format changed from 18 to 15 for 1.20.1
[Bell_Finds_All_Raiders_1_20_1.zip](https://github.com/user-attachments/files/17007481/Bell_Finds_All_Raiders_1_20_1.zip)
