### ISSUE TITLE
[1.18] [Take-a-Seat] Seat incorrectly tests for its location with a tag instead of testing for itself with a tag.

### ISSUE THREAD

**Issue by RITALINKo** [dragon3025/My-Datapacks#3]
**Describe the bug**
When i use the command to summon the llama, in the instant when it's summoned the llama dies

**To Reproduce**
use /trigger sit to spawn the llama
right click on the llama to sit

**Expected behavior**
I expected to be able to use the datapack to sit around, but when I right click on the llama it disappears xD

**Comment by dragon3025** [comment]
I tried it out and I'm not having this problem. Are you moving away from it after summoning it? It will despawn if you go move away from it.

I'm glad you posted this, because I accidentally realized I left the LLama visible.

**Comment by RITALINKo** [comment]
Heyy!! sorry for replying late (and for the bad english too, im not a native english speaker xD) but i was kinda busy.

I've been experimenting a little about what the error might have been, and it turns out that when you put the datapack on an Aternos server it doesn't work 100%, while in a singleplayer it goes great.

I recorded a video where i do the "comparison" using the datapack on the sv where i play with ma friends and the same map but in singleplayer.

[videos.zip](https://github.com/dragon3025/My-Datapacks/files/8028199/videos.zip)

this tells me that the file is very big so i uploaded it to a .zip  :> dunnoh if its gonna work but i hope so xD

Sorry for bothering you and the possible headache.
Also, thanks for the good care and the simpathy <3

Thank you in advance and have a nice day/night!

**Comment by dragon3025** [comment]
No problem, your last replay helped me discover a 2nd bug which is what's causing the issue. I accidentally told the Llama to execute the code **at** itself with a tag instead of **as** itself with a tag. I fixed it, and uploaded the the update to Planet Minecraft.
