### ISSUE TITLE
1.19 anti-ragon-grief - tall flowers not immunized

### ISSUE THREAD

**Issue by petersv5** [dragon3025/My-Datapacks#5]
**Describe the bug**
Tall flowers do not have the enderman_holdable tag that gets prmoted to dragon_immune. This makes them breakable by the ender dragon even with this datapack.

**To Reproduce**
Plant tall flowers and have a dragon fly over, e.g. by teleportation or enticing it. I use my ridable ender dragon datapack. The tal flowers get destroyed.

**Expected behavior**
No blocks affected by the ender dragon, including thetall flowers.

**Additional Notes**
I have submitted a pull request #4 that adds the flowers tag to dragon immune list. I am not sue of it would have been better to just have the tall_flowers tag. The flowers tag seemed to cast a wider net and thus more future proof.

**Comment by dragon3025** [comment]
Thank you, I merged it. Yeah [flowers](https://minecraft.fandom.com/wiki/Tag#:~:text=17w49b-,flowers,19w34a,-foxes_spawnable_on) contains tall_flowers, so it covers more.
