### ISSUE TITLE
1.19 - anti-ender-dragon-grief

### ISSUE THREAD

**Issue by petersv5** [dragon3025/My-Datapacks#7]
**Describe the bug**
Dragon can destroy skeleton and wither skeleton heads as well as wall forms of all heads.

**To Reproduce**
Enable the anti-ender-dragon-grief datapack.
Place skeleton heads on the ground or any heads on a wall and summon a dragon at the same location.
The heads are removed by the dragon.

**Expected behavior**
Heads should not be destroyed by the dragon.

**Additional Notes**
Proposed fix is submitted in PR #6.

**Comment by dragon3025** [comment]
Ah another, thank you. I merged it.
