### ISSUE TITLE
1.19.1 anti-dragon-grief

### ISSUE THREAD

**Issue by petersv5** [dragon3025/My-Datapacks#9]
**Describe the bug**
Frosted Ice is destroyed by the ender dragon.

**To Reproduce**
Place frosted ice in the world
Move ender dragon close to the frosted ice.

**Expected behavior**
The frosted ice should remain.

**Additional Notes**
Proposed fix submitted in PR #8.

**Comment by petersv5** [comment]
I accidentally pushed a second patch to the same pull request: adding wall versions of the torch types as well. Let me know if you want it broken out into separate pull requests.

**Comment by dragon3025** [comment]
Thank you, I merged it.
